package org.example.Service.AdminOps;

import org.example.Model.AdminOps.AdminTask;
import org.example.Model.AdminOps.AdminTaskPriority;
import org.example.Model.AdminOps.AdminTaskStatus;
import org.example.Model.User.User;
import org.example.Repository.UserRepository;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.List;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

public class AdminOpsService {

    private static final AtomicInteger TASK_SEQ = new AtomicInteger(1);
    private static final Map<Integer, AdminTask> TASKS = new ConcurrentHashMap<>();
    private static final Map<Integer, List<AdminTaskAuditEntry>> AUDIT = new ConcurrentHashMap<>();
    private static final Map<Integer, AdminRewardSnapshot> REWARDS = new ConcurrentHashMap<>();

    private final UserRepository userRepository;

    public AdminOpsService() {
        this.userRepository = new UserRepository();
    }

    public AdminOpsSnapshot getSnapshot(int adminId, String filter) {
        seedDefaultsIfNeeded(adminId);
        List<AdminTask> tasks = listTasks(adminId, filter);
        List<AdminTask> todo = new ArrayList<>();
        List<AdminTask> doing = new ArrayList<>();
        List<AdminTask> done = new ArrayList<>();
        for (AdminTask task : tasks) {
            if (task.getStatus() == AdminTaskStatus.DONE) done.add(task);
            else if (task.getStatus() == AdminTaskStatus.DOING) doing.add(task);
            else todo.add(task);
        }

        return new AdminOpsSnapshot(
                todo,
                doing,
                done,
                countUrgent(adminId),
                countOverdue(adminId),
                countCreatedToday(adminId),
                computeBeforeDeadlineRate(adminId),
                REWARDS.getOrDefault(adminId, new AdminRewardSnapshot(0, 0, 0, false)),
                new ArrayList<>(AUDIT.getOrDefault(adminId, List.of()))
        );
    }

    public void createTask(int actorAdminId, String title, String description, AdminTaskPriority priority, String tags, LocalDate dueDate) {
        if (title == null || title.isBlank()) throw new IllegalArgumentException("Le titre de la tache est obligatoire.");
        AdminTask task = new AdminTask();
        task.setId(TASK_SEQ.getAndIncrement());
        task.setTitle(title.trim());
        task.setDescription(sanitize(description));
        task.setStatus(AdminTaskStatus.TODO);
        task.setPriority(priority == null ? AdminTaskPriority.MEDIUM : priority);
        task.setTags(sanitize(tags));
        task.setDueDate(dueDate);
        task.setCreatedBy(actorAdminId);
        task.setAssignedTo(actorAdminId);
        task.setStarsEarned(0);
        task.setPosition(nextPosition(AdminTaskStatus.TODO));
        task.setAutoGenerated(false);
        TASKS.put(task.getId(), task);
        addHistory(task.getId(), actorAdminId, "CREATE", null, "TODO", "Creation manuelle", 0);
    }

    public void moveTask(int taskId, int actorAdminId, AdminTaskStatus targetStatus) {
        AdminTask task = TASKS.get(taskId);
        if (task == null) throw new IllegalArgumentException("Tache introuvable.");
        if (targetStatus == null || task.getStatus() == targetStatus) return;
        String from = task.getStatus().name();
        if (targetStatus == AdminTaskStatus.DONE) {
            boolean firstCompletion = task.getStarsEarned() <= 0;
            int stars = task.getStarsEarned() > 0 ? task.getStarsEarned() : calculateStars(task);
            task.setStatus(AdminTaskStatus.DONE);
            task.setCompletedAt(LocalDateTime.now());
            task.setStarsEarned(stars);
            task.setPosition(nextPosition(AdminTaskStatus.DONE));
            if (firstCompletion) {
                updateRewardsOnCompletion(actorAdminId, stars, stars * 20);
            }
            addHistory(taskId, actorAdminId, "MOVE_DONE", from, "DONE", "Deplacement vers DONE", stars);
            return;
        }

        // Si la tache revient hors DONE, on retire l'horodatage de completion.
        task.setStatus(targetStatus);
        task.setCompletedAt(null);
        task.setPosition(nextPosition(targetStatus));
        addHistory(taskId, actorAdminId, "MOVE", from, targetStatus.name(), "Changement colonne kanban", 0);
    }

    public int completeTask(int taskId, int actorAdminId) {
        AdminTask task = TASKS.get(taskId);
        if (task == null) throw new IllegalArgumentException("Tache introuvable.");
        if (task.getStatus() == AdminTaskStatus.DONE) return task.getStarsEarned();

        int stars = calculateStars(task);
        String from = task.getStatus().name();
        task.setStatus(AdminTaskStatus.DONE);
        task.setStarsEarned(stars);
        task.setCompletedAt(LocalDateTime.now());
        updateRewardsOnCompletion(actorAdminId, stars, stars * 20);
        addHistory(taskId, actorAdminId, "COMPLETE", from, "DONE", "Tache terminee", stars);
        return stars;
    }

    private List<AdminTask> listTasks(int adminId, String filter) {
        String f = filter == null ? "MY" : filter.trim().toUpperCase();
        boolean onlyMine = !"ALL".equals(f);
        boolean onlyUrgent = "URGENT".equals(f);
        boolean onlyOverdue = "OVERDUE".equals(f);

        List<AdminTask> rows = new ArrayList<>();
        for (AdminTask task : TASKS.values()) {
            if (onlyMine && task.getAssignedTo() != adminId) continue;
            if (onlyUrgent && task.getPriority() != AdminTaskPriority.URGENT) continue;
            if (onlyOverdue && !task.isOverdue()) continue;
            User assigned = findAdminById(task.getAssignedTo());
            task.setAssignedEmail(assigned == null ? "admin" : assigned.getEmail());
            rows.add(task);
        }
        rows.sort(Comparator
                .comparing((AdminTask t) -> t.getStatus().ordinal())
                .thenComparingInt(AdminTask::getPosition)
                .thenComparing(AdminTask::getId));
        return rows;
    }

    private int countUrgent(int adminId) {
        int c = 0;
        for (AdminTask t : TASKS.values()) {
            if (t.getAssignedTo() == adminId && t.getStatus() != AdminTaskStatus.DONE && t.getPriority() == AdminTaskPriority.URGENT) c++;
        }
        return c;
    }

    private int countOverdue(int adminId) {
        int c = 0;
        for (AdminTask t : TASKS.values()) {
            if (t.getAssignedTo() == adminId && t.isOverdue()) c++;
        }
        return c;
    }

    private int countCreatedToday(int adminId) {
        int c = 0;
        for (AdminTask t : TASKS.values()) {
            if (t.getAssignedTo() == adminId && t.getCompletedAt() == null) c++;
        }
        return c;
    }

    private double computeBeforeDeadlineRate(int adminId) {
        int withDeadline = 0;
        int doneInTime = 0;
        for (AdminTask t : TASKS.values()) {
            if (t.getAssignedTo() != adminId) continue;
            if (t.getStatus() != AdminTaskStatus.DONE || t.getDueDate() == null || t.getCompletedAt() == null) continue;
            withDeadline++;
            if (!t.getCompletedAt().toLocalDate().isAfter(t.getDueDate())) doneInTime++;
        }
        if (withDeadline == 0) return 0.0;
        return (doneInTime * 100.0) / withDeadline;
    }

    private int calculateStars(AdminTask task) {
        int stars = 1;
        if (task.getDueDate() != null && !LocalDate.now().isAfter(task.getDueDate())) stars++;
        String tags = task.getTags() == null ? "" : task.getTags().toUpperCase();
        if (task.getPriority() == AdminTaskPriority.URGENT || tags.contains("SECURITY")) stars++;
        return Math.min(3, stars);
    }

    private void updateRewardsOnCompletion(int adminId, int stars, int points) {
        AdminRewardSnapshot old = REWARDS.getOrDefault(adminId, new AdminRewardSnapshot(0, 0, 0, false));
        int streak = Math.max(1, old.streakDays());
        REWARDS.put(adminId, new AdminRewardSnapshot(
                old.totalStars() + stars,
                old.totalPoints() + points,
                streak,
                true
        ));
    }

    private void addHistory(int taskId, int actorAdminId, String action, String fromStatus, String toStatus, String note, int stars) {
        User actor = findAdminById(actorAdminId);
        String email = actor == null ? "admin" : actor.getEmail();
        AdminTaskAuditEntry entry = new AdminTaskAuditEntry(
                taskId,
                action,
                fromStatus,
                toStatus,
                email,
                stars,
                LocalDateTime.now()
        );
        AUDIT.computeIfAbsent(actorAdminId, k -> new ArrayList<>()).add(0, entry);
        List<AdminTaskAuditEntry> entries = AUDIT.get(actorAdminId);
        if (entries.size() > 50) entries.remove(entries.size() - 1);
    }

    private int nextPosition(AdminTaskStatus status) {
        int max = 0;
        for (AdminTask t : TASKS.values()) {
            if (t.getStatus() == status) max = Math.max(max, t.getPosition());
        }
        return max + 1;
    }

    private void seedDefaultsIfNeeded(int adminId) {
        boolean hasMine = TASKS.values().stream().anyMatch(t -> t.getAssignedTo() == adminId);
        if (hasMine) return;
        createTask(adminId, "Verifier KYC en attente", "Controler les dossiers KYC en attente.", AdminTaskPriority.HIGH, "KYC,COMPLIANCE", LocalDate.now().plusDays(1));
        createTask(adminId, "Revoir alertes securite", "Analyser les tentatives de login suspectes.", AdminTaskPriority.URGENT, "SECURITY,RISK", LocalDate.now());
        createTask(adminId, "Suivi tickets support", "Traiter les demandes client en cours.", AdminTaskPriority.MEDIUM, "SUPPORT", LocalDate.now().plusDays(2));
    }

    private String sanitize(String value) {
        if (value == null) return "";
        return value.trim().replace("<", "").replace(">", "");
    }

    public User findAdminById(int id) {
        List<User> users = userRepository.findAll();
        for (User user : users) {
            if (user.getId() == id) return user;
        }
        return null;
    }
}
