## Local secrets for FinTrust mail (do not commit real values)
## Copy to: fintrust.local.properties and fill values.

FINTRUST_SMTP_HOST=smtp.gmail.com
FINTRUST_SMTP_PORT=587
FINTRUST_SMTP_STARTTLS=true
FINTRUST_SMTP_FROM=mohamedhedi322@gmail.com
FINTRUST_SMTP_DEBUG=true
FINTRUST_SMTP_USERNAME=mohamedhedi322@gmail.com
FINTRUST_SMTP_APP_PASSWORD=xnir pkyn brkj yxcg