package org.example.Model.AdminOps;

import java.time.LocalDate;
import java.time.LocalDateTime;

public class AdminTask {
    private int id;
    private String title;
    private String description;
    private AdminTaskStatus status;
    private AdminTaskPriority priority;
    private String tags;
    private LocalDate dueDate;
    private int createdBy;
    private int assignedTo;
    private String assignedEmail;
    private int starsEarned;
    private LocalDateTime completedAt;
    private int position;
    private boolean autoGenerated;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public AdminTaskStatus getStatus() {
        return status;
    }

    public void setStatus(AdminTaskStatus status) {
        this.status = status;
    }

    public AdminTaskPriority getPriority() {
        return priority;
    }

    public void setPriority(AdminTaskPriority priority) {
        this.priority = priority;
    }

    public String getTags() {
        return tags;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public LocalDate getDueDate() {
        return dueDate;
    }

    public void setDueDate(LocalDate dueDate) {
        this.dueDate = dueDate;
    }

    public int getCreatedBy() {
        return createdBy;
    }

    public void setCreatedBy(int createdBy) {
        this.createdBy = createdBy;
    }

    public int getAssignedTo() {
        return assignedTo;
    }

    public void setAssignedTo(int assignedTo) {
        this.assignedTo = assignedTo;
    }

    public String getAssignedEmail() {
        return assignedEmail;
    }

    public void setAssignedEmail(String assignedEmail) {
        this.assignedEmail = assignedEmail;
    }

    public int getStarsEarned() {
        return starsEarned;
    }

    public void setStarsEarned(int starsEarned) {
        this.starsEarned = starsEarned;
    }

    public LocalDateTime getCompletedAt() {
        return completedAt;
    }

    public void setCompletedAt(LocalDateTime completedAt) {
        this.completedAt = completedAt;
    }

    public int getPosition() {
        return position;
    }

    public void setPosition(int position) {
        this.position = position;
    }

    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    public void setAutoGenerated(boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    public boolean isOverdue() {
        return dueDate != null && status != AdminTaskStatus.DONE && dueDate.isBefore(LocalDate.now());
    }
}

